[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[functions]]
  name = "chat"
  timeout = 26

[[functions]]
  name = "pitchers"
  timeout = 20

[[functions]]
  name = "odds"
  timeout = 20
